[functions]
  directory="functions"

[build]
  command="make build"
  publish="./frontend/.next"
  functions="nt-functions"

[build.environment]
  GO_VERSION="1.19"

[[plugins]]
  package="@netlify/plugin-nextjs"
