[functions]
  directory="nt-functions"

[build]
  command="make build-nt"
  publish="./frontend/.next"
  functions="functions"

[build.environment]
  GO_VERSION="1.19"

[[plugins]]
  package="@netlify/plugin-nextjs"
