service: steamapp-details

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  environment:
    TABLE_NAME: apps-${opt:stage, sls:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:*"

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8001
      inMemory: true
      migrate: true

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  appDetails:
    handler: ./functions/get/get.go
    events:
      - http:
          path: apps
          method: get

resources:
  Resources:
    UsersCRUDDynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'apps-${opt:stage, sls:stage}'
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
